### ISSUE TITLE
How to get camera linear and angular speed for every frame ?

### ISSUE THREAD

**Issue by taiping-z** [JakobEngel/dso#103]
Hi, @JakobEngel 

I want to calculate **linear and angular speed** from two consecutive frames. 

Here is what I do.
In the function `void SampleOutputWrapper::publishCamPose(FrameShell* frame, CalibHessian* HCalib)`, after two images input, previous and current camera poses, named `preCamPose, curCamPose` are available. 

Then, I calculate transformation between the previous and current frame.
```
SE3 SE3_pre  = preCamPose.camToWorld; 
SE3 SE3_cur = curCamPose.camToWorld; 
SE3 Transform = SE3_cur*SE3_pre.inverse(); 
```
According to Transform, rotation angle and translation distance can be calculated. 
```
Eigen::Vector3d translation =  Transform.translation();
Eigen::Matrix3d rotation = Transform.rotationMatrix();

double rotate_x = atan2((double)rotation(2,1) , (double)rotation(2,2));
double rotate_y = atan2((double)-rotation(2,0), (double)sqrt((double)(rotation(2,1)*rotation(2,1) +rotation(2,2)*rotation(2,2))));
double rotate_z = atan2((double)rotation(1,0), (double)rotation(0,0));
double trans_x = translation(0);
double trans_y = translation(1);
double trans_z = translation(2);
```
I tested this code based on KITTI dateset.
Here is the **result** when the car goes straight.
```
translation 
-0.00215287
-0.00192859
0.0378226
rotationMatrix 
           1  5.93416e-06 -0.000741771
-4.88947e-06     0.999999   0.00140837
 0.000741779  -0.00140837     0.999999
 rotation x:-0.00140837,y:-0.000741779,z:-4.88947e-06
translation x:-0.00215287,y:-0.00192859,z:0.0378226
```
The **result** when the car turns.
```
translation 
-0.17997
0.00874461
0.00839679
rotationMatrix 
   0.997901 0.000449692   0.0647537
-0.000246857    0.999995 -0.00314037
 -0.0647548   0.0031178    0.997896
rotation x:0.00312436,y:0.0648002,z:-0.000247376
translation x:-0.17997,y:0.00874461,z:0.00839679
```
**Here is my question**.(Presumed, the x-axis is the forward direction, the z-axis is perpendicular to the ground.) 
When the car goes straight, the translation should be in only one direction x-axis. When the car turns, there should be a large rotation angle around the z-axis. Obviously, this is not the case in my above-tested results.

Am I wrong to calc speed in this way?  What can I do to get translation in one direction, and the rotation angle around the axis perpendicular to the ground?
Any help would be greatly appreciated.

Regards
Taiping
Oct 21, 2017

**Comment by chabaudmorgan** [comment]
> (Presumed, the x-axis is the forward direction, the z-axis is perpendicular to the ground.)

There you go, wrong presumption! ^^

Coordinates are in image frame: x-axis is on image columns, y-axis is on image lines, z axis is "forward" (depth)

**Comment by taiping-z** [comment]
@chabaudmorgan , thank you very much for your reply. I have already solved this problem.
Regards,
Taiping

**Comment by NikolausDemmel** [comment]
Closing, since it seems resolved.
