### ISSUE TITLE
How to run the project on the TUM mono-datasset?

### ISSUE THREAD

**Issue by SouthEastleo** [JakobEngel/dso#104]
I have downloaded the dataset already ,but I can't find the calibration file and the gamma、vignette.Should I create a camera.txt by myself? thanks !

**Comment by SouthEastleo** [comment]
OK.I haven't solved this problem, because that I downloaded a wrong data set.

**Comment by SouthEastleo** [comment]
OK.I have solved this problem, because that I downloaded a wrong data set.

**Comment by lorhm** [comment]
How do you run the programme, once you have completed the build, cmake, make procedures shown in the README.md?

**Comment by NikolausDemmel** [comment]
https://github.com/JakobEngel/dso#3-usage

**Comment by lorhm** [comment]
Thank you for your reply.
I found out my build was not complete, as a result the "bin" folder was not created.
Got it working now, thanks !
