### ISSUE TITLE
Can the generated result file be in PCD format?

### ISSUE THREAD

**Issue by mrwtakev** [JakobEngel/dso#114]
Hello，
I successfully run this program and found that the generated point cloud file is txt format,can the generated result file be in PCD format?

**Comment by NikolausDemmel** [comment]
I'm not sure saving the pointcloud to a text file is implemented, or is it? And also not pcd. But PR's are welcome.

**Comment by mrwtakev** [comment]
I see the result file is Result.txt, how can I convert its output format? For example, PR?

**Comment by NikolausDemmel** [comment]
`result.txt` contains camera poses, as described in the readme. I suggest to also check the code to see whats implemented.

PR means pull request, i.e. you are welcome to implement this yourself and provide a pull request to merge it back for the benefit of others. It also means that no-one is currently planning to implement this.

**Comment by mrwtakev** [comment]
Thank you
