### ISSUE TITLE
Could it be possible to make a real-time-streaming DSO?

### ISSUE THREAD

**Issue by sun0shine** [JakobEngel/dso#115]
Hello guys, I already run DSO with dso_dataset launchfile and provided datasets like sequence_01, sequence_02...
But the issue what i want is running dso in real-time-streaming.
Can i make it while i'm recording with my smart-phone? or Is there anybody going on like this methods?

**Comment by NikolausDemmel** [comment]
DSO implements linearized, single-threaded processing, as well as multi-threaded "real time" processing. Check out https://github.com/JakobEngel/dso_ros for an example of how to use DSO with live camera input.

**Comment by sun0shine** [comment]
@NikolausDemmel Thanks :)

**Comment by lcqwe** [comment]
Is there any method for making a real-time-streaming DSO on windows with a mono camera. or says that How can I use no-ros wrapper for this thing?

**Comment by NikolausDemmel** [comment]
@lcqwe, you will probably have to write your own wrapper that receives the images somehow (e.g. camera driver) and passes them on to DSO. You can take the ROS wrapper as an example of what to do.
