### ISSUE TITLE
bug in CoarseInitializer::doStep

### ISSUE THREAD

**Issue by kokerf** [JakobEngel/dso#137]
Hi JaKob,
    I wonder whether there is a bug in [CoarseInitializer::doStep](https://github.com/JakobEngel/dso/blob/master/src/FullSystem/CoarseInitializer.cpp#L895).

the code is:
```c++
		float b = JbBuffer[i][8] + JbBuffer[i].head<8>().dot(inc);
		float step = - b * JbBuffer[i][9] / (1+lambda);
```
I think it should be '/' rather than '*' in the second line:
```c++
                float step = - b / JbBuffer[i][9] / (1+lambda);
```
we can state the system as:

![sys](https://user-images.githubusercontent.com/16713039/39361598-dabbcb82-4a55-11e8-8a9a-feccceb75fef.png)

the $\delta \xi$  contain the pose and affine parameters which is sloved(`inc`) by Schur complement ahead, and we want to calculate the inverse depth $\delta d$. I slove the answer as:

![slove](https://user-images.githubusercontent.com/16713039/39361737-5f67fbf8-4a56-11e8-8dbe-bbbedcf9ac6f.png)

in [here](https://github.com/JakobEngel/dso/blob/master/src/FullSystem/CoarseInitializer.cpp#L445) and [here](https://github.com/JakobEngel/dso/blob/master/src/FullSystem/CoarseInitializer.cpp#L927) we get correspondences:

![resp](https://user-images.githubusercontent.com/16713039/39362583-8c383294-4a59-11e8-88cb-8c1bc5c9149c.png)

So there should be the inverse of `JbBuffer[i][9]`. Look forward to your answer.

**Comment by blindnote** [comment]
It's inversed [here](https://github.com/JakobEngel/dso/blob/e59db70710ead30d6b47959f886665ddd9cb4f85/src/FullSystem/CoarseInitializer.cpp#L555)

**Comment by kokerf** [comment]
@blindnote thank you! I found it!
