### ISSUE TITLE
Is there an available code for VI-DSO? (DSO combined with IMU)

### ISSUE THREAD

**Issue by ronir121** [JakobEngel/dso#148]
The paper for visual-inertial odometry looks very interesting, is there an available source code for it?
( https://vision.in.tum.de/research/vslam/vi-dso )

**Comment by NikolausDemmel** [comment]
Not for the moment unfortunately. It is unclear if and when it might be published.

**Comment by garethblock** [comment]
Hi @NikolausDemmel, agreed with ronir121 -- the VI-DSO looks like a great addition.  I would really like to run the source code on our datasets... is it possible to provide access?  Thanks!

**Comment by NikolausDemmel** [comment]
It's not in my hands and as far as I know it is not possible. Sorry.

I'll close the issue since I guess it has been answered.

**Comment by lukasvst** [comment]
A (late) update on this: An official implementation for the successor of VI-DSO is now available at: https://github.com/lukasvst/dm-vio
