### ISSUE TITLE
Pangolin shows only first few frames and then stops

### ISSUE THREAD

**Issue by Nihaar1996** [JakobEngel/dso#155]
<img width="1440" alt="screen shot 2018-07-17 at 23 38 32" src="https://user-images.githubusercontent.com/13466078/42849315-964a36d2-8a1a-11e8-9f42-cba5e6af9e1a.png">
<img width="1427" alt="screen shot 2018-07-17 at 23 34 05" src="https://user-images.githubusercontent.com/13466078/42849151-ff2722d8-8a19-11e8-97a3-32700096bccc.png">

Pangolin initialises and displays few frames (say about 10) and then just freezes, as if it is waiting for something to happen. There is no error thrown in the terminal output just that it stops at the place shown in the attahced figure.

This is for a mac. Any help is greatly appreciated!

**Comment by NikolausDemmel** [comment]
Hmmm, not sure. I think I might have seen that before.

Some thoughts:

 - maybe try the `nomt=1` and `speed=0` options.
 - try to debug / add some output to check where exactly it is blocking.
 - try on Ubuntu, if possible

**Comment by Nihaar1996** [comment]
Oh that's super advice, @NikolausDemmel that worked! Many, many thanks!

**Comment by whubaichuan** [comment]
@nihaarshah Please use Linux. Many problems in mac will not exist in Linux.
