### ISSUE TITLE
Has anyone implemented vi-dso successfully?

### ISSUE THREAD

**Issue by vonzy** [JakobEngel/dso#182]
For the past several months, I have spared no effect to implement vi-dso, but I found it's too hard.

The biggest problem I meet is the rank deficiency of system matrix, since monocular visual-inertial odometry has 4DOF, which means the yaw and the absolute position are unobservable. But in the paper of vidso, the author estimate extra gravity and scale explicitly online with G-N method unlike other tightly-coupled approaches. When I try to implement this approach in vi-dso, the hessian I get is ill-conditioned, it seems imposible to get a good solution. I wonder how to handle ill system matrix to get accurate and stable results.

**Comment by vonzy** [comment]
Problem solved

**Comment by Tilgaard** [comment]
Hey Vonzy
Could you please share your solution? Would be nice if you could share your code.

**Comment by vonzy** [comment]
@Tilgaard I am still trying to improve the performance of the estimator, if everything is ok, I'll release the code.

**Comment by robbel** [comment]
Hi @vonzy did you ever manage to solve the issues and still consider releasing the associated code? Cheers

**Comment by lukasvst** [comment]
A (late) update on this: An official implementation for the successor of VI-DSO is now available at: https://github.com/lukasvst/dm-vio
