### ISSUE TITLE
About Fusion DSO and IMU for Absolute Scale Estimation

### ISSUE THREAD

**Issue by studennis911988** [JakobEngel/dso#187]
Hi, everyone, I'm currently working on fusion visual odometry(DSO) with imu to get absolute scale estimation, and I had read the issue #105  and #36.
The procedure I'm looking for is loosely-coupled filter-based method, and the well-established framework [msf](https://github.com/ethz-asl/ethzasl_msf) turned out to be overwhelming for my system, since I only need the position and scale estimation. 
Therefore I found the paper 
[Fusion of IMU and Vision for Absolute Scale Estimation
in Monocular SLAM](https://www.ifi.uzh.ch/dam/jcr:e885ca94-b971-4bcb-be00-c04b67bebfaa/UAV10_nuetzi.pdf), which algorithm looks much easy and realizable.

I had got the DSO data and implemented the paper algorithm by MATLAB, but even how hard I tuned the parameters of each states( position, velocity, acceleration, scale) in processing  covariance and measurement covariance, and It just can't work properly.

-  raw DSO data(red line) and ground truth(black dash line) in same axis
![github ask](https://user-images.githubusercontent.com/43871350/59317832-307fbf80-8cf7-11e9-8e8b-d979981540aa.jpg)

**You can see clearly an initial offset caused by initialization on monocular slam and a scale difference between ground truth(in metric) and visual odometry(without scale)**

-  After I reduce the offset manually
![GITHUBASKjpg](https://user-images.githubusercontent.com/43871350/59317967-ed721c00-8cf7-11e9-9c57-d3aa35b10f39.jpg)

**You can see the scale is roughly around 0.5 ( DSO * 0.5 = ground truth)**

-  If I fuse DSO(black dash line) and IMU without scale, the result(red line) looks fine without fine tuned parameters
![dso fusion](https://user-images.githubusercontent.com/43871350/59318248-e5ff4280-8cf8-11e9-9a44-8a56cc0710c2.jpg)

- The best result (tuning by Genetic Algorithm) including scale in state and apply the proposed algorithm in  [Fusion of IMU and Vision for Absolute Scale Estimation
in Monocular SLAM](https://www.ifi.uzh.ch/dam/jcr:e885ca94-b971-4bcb-be00-c04b67bebfaa/UAV10_nuetzi.pdf)
p.s DSO data (blue line) , fusion data(orange line)

![gatune](https://user-images.githubusercontent.com/43871350/59318513-e3511d00-8cf9-11e9-93d9-692d30966f7c.jpg)

My guess about the failure is the scale estimate value is wrong, even although I had give the initial   guess close to 0.5, which is the roughly true scale.

My question is 

1.  Has anyone work successfully on this algorithm ? Or any suggestion on this method?
2.  Has anyone try another loosely-coupled filter-based method for visual-inertia fusion?
3.  Moreover, ANY comment is welcomed!
Thanks in advanced!

**Comment by studennis911988** [comment]
problem solved !

**Comment by jack-scott** [comment]
How did you fix this problem?

**Comment by studennis911988** [comment]
I put the "unscale" part in measurement and tune by GA, and the results look fine.
![2086480](https://user-images.githubusercontent.com/43871350/59767551-24869580-92d5-11e9-8c7d-25c6a577e9d7.jpg)
