### ISSUE TITLE
how to save the pointcloud

### ISSUE THREAD

**Issue by fyj3266098** [JakobEngel/dso#19]
if you do not have realize the function of saving pointcloud ,can you tell me which variables have save the pointcloud.

**Comment by JakobEngel** [comment]
please have a look at src/IOWrapper/Output3DWrapper.h, in that file there is a short description of the classes / structs used. You can then create an Output3DWrapper implementation and incrementally create the pointcloud by hooking into the Output3DWrapper::publishKeyframes() function (again, see Output3DWrapper.h).

By default, the core DSO algorithm does not save marginalized keyframes internally to avoid ever-growing memory requirements - they are only stored for visualization in the PangolinDSOViewer.

**Comment by fyj3266098** [comment]
I have save the point cloud in refreshPC of KeyFrameDisplay.cpp where i write the tmpVertexBuffer[vertexBufferNumPoints] to files every time and corresponding R&T which could convert the camera coordinate to world coordinate. Do you think is it right?

**Comment by shikailei** [comment]
hello,can you save pointcloud now?

**Comment by GentlemanCheng** [comment]
hello,can you save the dso pointcloud now?
