### ISSUE TITLE
how to obtain the camera following view like the demo

### ISSUE THREAD

**Issue by amiltonwong** [JakobEngel/dso#2]
Hi, @JakobEngel ,

Thank you so much for releasing such an impressive VO system. Result is inspiring and impressive. One thing I'd like to ask: After running the package, the [mapping result](https://www.dropbox.com/s/6fzk0re9a8yl5wo/2016-11-13_234746.jpg?dl=0) is obtained. How could I obtain the similar camera following view like the demo in https://youtu.be/C6-xwSOOdqQ? (which shows much dynamics.) Is that the function from Pangolin, or just manually switching the view?

Thanks~

**Comment by JakobEngel** [comment]
That camera animation is actually a functionality I made for the LSD-SLAM videos, it's still in the lsd_slam_viewer code (although entirely undocumented; see around PointCloudViewer.cpp:180-230 in the lsd_slam repository) - which I also used for the DSO video.
I only switched from ROS/qglviewer to Pangolin for the open-source version of DSO, to avoid all the issues arising from ROS & different operating systems; unfortunately, that means the animation playback functionality is not available any more. 
I imagine Pangolin has some similar functionality though...
