### ISSUE TITLE
How to run a dataset from https://vision.in.tum.de/mono-dataset

### ISSUE THREAD

**Issue by martino92** [JakobEngel/dso#233]
what is ''bin/dso_dataset"?
	bin/dso_dataset \
		files=XXXXX/sequence_XX/images.zip \
		calib=XXXXX/sequence_XX/camera.txt \
		gamma=XXXXX/sequence_XX/pcalib.txt \
		vignette=XXXXX/sequence_XX/vignette.png \
		preset=0 \
		mode=0

**Comment by martino92** [comment]
figured it out

**Comment by IldarGreat** [comment]
@martino92 so what is ''bin/dso_dataset"?
