### ISSUE TITLE
Output File

### ISSUE THREAD

**Issue by dgkntrz** [JakobEngel/dso#236]
Hello,

Other algorithms I've seen so far provide a keyframe trajectory file at the end of the run, for us to compare with the ground truth. Does this algorithm save such a file as well?

Thanks!

**Comment by NikolausDemmel** [comment]
From the readme:

> Per default, dso_dataset writes all keyframe poses to a file result.txt at the end of a sequence, using the TUM RGB-D / TUM monoVO format ([timestamp x y z qx qy qz qw] of the cameraToWorld transformation).
