### ISSUE TITLE
Running on Euroc MAV dataset

### ISSUE THREAD

**Issue by andre-nguyen** [JakobEngel/dso#25]
Hi,

how did you manage to run dso on the Euroc MAV dataset? I was about to attempt but then I realized I wouldn't be able to get the gamma and vignette calibration since they don't provide that kind of calibration data.

Thanks,

**Comment by andre-nguyen** [comment]
Oops, I misunderstood the readme. I get it now!

**Comment by Yelen719** [comment]
How was the performance on EuRoC MAV?

**Comment by andre-nguyen** [comment]
It was great actually, now if only I knew how to use GTSAM or something to scale the measurements...

**Comment by 447425299** [comment]
@andre-nguyen  I have run dso on EUROC, but the performance is not very good, Are you sure it is great on EUROC?

**Comment by andre-nguyen** [comment]
I used it on one of the machine hall bags and the point cloud was actually pretty nice and the vehicle came back really not for from its starting point. I have no other comparison criteria or performance data to show.

**Comment by 447425299** [comment]
ok thanks

**Comment by zhehangT** [comment]
hi, how did you define the  calibration data of EUROC, please?
Can you give any examples, please?
@andre-nguyen

**Comment by SkyRiderMike** [comment]
How can you run this program on EuRoC ? @andre-nguyen

**Comment by andre-nguyen** [comment]
This thread is almost a year old, I suggest just reading the Readme carefully, seems like it worked for me and others in the past.

**Comment by hobbeshunter** [comment]
I used

```
KannalaBrandt 460.92587684824869 459.56960125805508 365.90627988127127 249.33982146124706 -0.004161020735327023 0.02326805021977024 -0.02673515372903321 0.011272262685694161
752 480
crop
752 480
```

for cam0
