### ISSUE TITLE
Does this a typo in readFromFile?

### ISSUE THREAD

**Issue by sunstarchan** [JakobEngel/dso#27]
The code at following line

https://github.com/JakobEngel/dso/blob/master/src/util/Undistort.cpp#L849

`if(benchmarkSetting_width != 0)`
`{`
`    h = benchmarkSetting_height;`
`    if(outputCalibration[0] == -3)`
`    outputCalibration[0] = -1;  // crop instead of none, since probably resolution changed.`
`}`

the condition is on purpose or just a typo?

Thanks

**Comment by JakobEngel** [comment]
yes - probably should be "if(benchmarkSetting_height != 0)". I've always either overwritten both width and height or none, so it didn't really matter ;).
