### ISSUE TITLE
long int interpreted as 32 bit in 32 bit systems...

### ISSUE THREAD

**Issue by mah92** [JakobEngel/dso#32]
Hi
long data type is 32 bit in 32 bit systems and 64bit in 64 bit ones.
Compiling the code in 32 bit systems causes a lot of warning like:
"warning: right shift count >= width of type"
The problem is real as shifting 32 bit variables has different result than 64 bit variables.
Replacing all "long" and "long int" variables by int64_t (except in DatasetReader.h) solved the problem.

**Comment by JakobEngel** [comment]
who new... thanks. I kinda assumed long would be 64 bit everywhere. Fixed in the devel branch, since may break compatibility with the Output3DWrapper.

**Comment by mah92** [comment]
Conversely, I didn't know it can be 64 bit either! I'm grown in a 32bit world!!;-)
