### ISSUE TITLE
API document

### ISSUE THREAD

**Issue by gogojjh** [JakobEngel/dso#35]
Will you provide the additive API document of this code?

**Comment by JakobEngel** [comment]
To be honest, probably not. The closest to an API is the documentation in 
https://github.com/JakobEngel/dso/blob/master/src/IOWrapper/Output3DWrapper.h
and the example in 
https://github.com/JakobEngel/dso/blob/master/src/IOWrapper/OutputWrapper/SampleOutputWrapper.h

That should be enough to figure out how to use the code, and integrate it into your own project. 
If you want to go deeper, you will have to figure out what does what yourself, the paper ( http://vision.in.tum.de/_media/spezial/bib/engel2016dso.pdf ) should help with that. 

It should be mentioned that the code is the result of a fairly long-lasting research project, during the course of which it has been re-written and re-factored many many times ... Thus, from a "software-engineering" standpoint it is probably quite terrible ;).

**Comment by mah92** [comment]
Hi, I had some questions, what is the CPAR variable set to 4?

**Comment by JakobEngel** [comment]
CPAR is the number of camera intrinsic parameters that are calibrated on-line (fx, fy, cx, cy by default) - I have however never tested any other number. 
The parameters in settings.cpp that do not have any description can mostly be kept as they are, you should not have to change them for anything really - I just have a habit of collecting all possible parameters / settings in one central place.

**Comment by s3r637** [comment]
The initialization part (CoarseInitializer) differs from the tracking part (CoarseTracker) wasn't mentioned in the paper, right? The paper describes only the part which continuously update the existing motion model.

**Comment by NikolausDemmel** [comment]
Closing since the question seems answered / due to lack of activity.
