### ISSUE TITLE
Error building dso-slam with Visual Studio

### ISSUE THREAD

**Issue by wystnphux** [JakobEngel/dso#39]
I get an error building dso-slam with Visual Studio 2015. The first error message is as follows:

>Error	C2976	'std::deque': too few template arguments	dso	C:\XXX\dso-slam\dso\src\FullSystem\FullSystem.h	310	

Line 310 of FullSystem.h:
`std::deque<FrameHessian*> unmappedTrackedFrames;`

Is this related to the the definition of `struct FrameHessian` in HessianBlacks.h?

Actually, I'd like to fix this issue but I don't know where to start searching. Maybe there is someone more experienced that may give a hint on this. What would be useful information to look at?

Kind regards

PS: And why does boost come into play? May this be a hint for an incompatibility to my current boost version (1.63)?
>C:\XXX\dso-slam\dso\src\FullSystem/FullSystem.h(310): error C2976: 'std::deque': too few template arguments
>C:\libs\boost\v1.63.0\boost/detail/container_fwd.hpp(131): note: see declaration of 'std::deque'

**Comment by wystnphux** [comment]
An `#include <deque>` above all other includes did solve the problem.

**Comment by JakobEngel** [comment]
can you create a pull request with the added includes? or let me know where exactly you had to add them? thanks!

**Comment by fszeliga** [comment]
@wystnphux hey, did you have to do anything special to run dso under visual studio? I have a weird unresolved symbol when initializing FullSystem (other components of dso_dataset work just fine)...

**Comment by NikolausDemmel** [comment]
Closing since the question seems answered / due to lack of activity.
