### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [JakobEngel/dso#4]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [AccumulatedSCHessianSSE](https://github.com/JakobEngel/dso/blob/f6e43e277a8e6f606265c1d90fd7549e475e6ea6/src/OptimizationBackend/AccumulatedSCHessian.h#L54 "Destructor for AccumulatedSCHessianSSE")
- [EnergyFunctional::setAdjointsF](https://github.com/JakobEngel/dso/blob/f6e43e277a8e6f606265c1d90fd7549e475e6ea6/src/OptimizationBackend/EnergyFunctional.cpp#L44 "EnergyFunctional::setAdjointsF function")
- [PrepImageItem:release](https://github.com/JakobEngel/dso/blob/f6e43e277a8e6f606265c1d90fd7549e475e6ea6/src/util/DatasetReader.h#L92 "PrepImageItem::release function")

**Comment by JakobEngel** [comment]
Huh, I didn't actually know that you can call delete on a nullpointer without blowing things up...  that does simplify things ^^.

**Comment by elfring** [comment]
Which commits will contain [corresponding software improvements](http://en.cppreference.com/w/cpp/language/delete "Description for delete expressions")?
