### ISSUE TITLE
Cal File Bug

### ISSUE THREAD

**Issue by idxExtropy** [JakobEngel/dso#44]
I started experimenting with DSO this morning, very impressive!

In camera.txt, I found the the string "Equidistant" in the instructions must be "EquiDistant" with a capital "D" in order to be parsed.  Additionally, the "UndistortEquidistant function should have a capital "D" to match.

The snprint on line 762 (nPars ==  8) had 10 floating point inputs and not 8.  Didn't test to see if that mattered. 

Cheers!

**Comment by JakobEngel** [comment]
fixed. thanks!
