### ISSUE TITLE
Very low FPS in Visual Studio

### ISSUE THREAD

**Issue by lshGame** [JakobEngel/dso#47]
Hey guys. I managed to compile DSO with visual studio2013, but DSO(release) ran at a very low FPS( 4 fps after initialization).
While compiling the release version of DSO, visual studio stuck in "generating code" with Optimization /O2 on. SO I disabled optimization. Is there any way to turn on /O2?
by the way, My CPU is i7-3610QM.

**Comment by JakobEngel** [comment]
I myself have never used Visual Studio, so I cannot answer your question. However, I can confirm that when compiling without full optimization (or even in debug mode), DSO will be very slow, in particular due to the heavy use of Eigen.

**Comment by lshGame** [comment]
Thanks for your reply. My problem is solved. The cause of the issue is that I used Eigen3 which was not compiled. Now, DSO runs at 20FPS(tum dataset) in windows. Awesome work!

**Comment by Lucky8Young** [comment]
@lshGame I'm very sorry to bother you, friend. I want to compile DSO with vs2013, but I don't know how to  
do it successfully. I have tried several times but all failed. Could you please tell me how to do it or give some advices? Thank you very much!

**Comment by jhincapie** [comment]
I am also interested in compiling with VS, but have not been successful. Anyone knows the steps?

**Comment by YJCITA** [comment]
@lshGame  I'm very sorry to bother you. But I wonder what's "I used Eigen3 which was not compiled" mean? As I know, Eigen3 is header files?

**Comment by lshGame** [comment]
@YJCITA You're right that Eigen3 is header files, which means it's not necessary to compile it. But if you met the same low FPS problem in windows, you can try it. It may work

**Comment by lshGame** [comment]
@Lucky8Young @jhincapie @fszeliga I'm terribly sorry to reply late. If you still want to compile dso in windows with VS2013, you can refer to this article. https://mp.weixin.qq.com/s/5k_lX7Dof65AzI7uBC9HUg

**Comment by NikolausDemmel** [comment]
Closing since the question seems answered / due to lack of activity.
