### ISSUE TITLE
Loop closing and coordinate transform

### ISSUE THREAD

**Issue by dark1451** [JakobEngel/dso#50]
I wonder why the DSO-SLAM isn't implemented loop closing algorithm using OpenFABMAP.

Another question is that I want know any transform methods relative coordinate(camera) to absolute coordinate(world).

Thank you.

(shlee2@geotwo.com)

**Comment by s3r637** [comment]
Hi @dark1451,

DSO is a pure odometry algorithm. It isn't a SLAM this means no loop closing.

Your second concern I do not understand. Maybe you could provide more explanation?

cheers
