### ISSUE TITLE
Maybe it's a bug in CoarseInitializer::calcResAndGS()

### ISSUE THREAD

**Issue by hhgzljp** [JakobEngel/dso#52]
line 506 and 511, should E be EAlpha?

	498: // calculate alpha energy, and decide if we cap it.
	499: Accumulator11 EAlpha;
	500: EAlpha.initialize();
	501: for(int i=0;i<npts;i++)
	502: {
	503: 	Pnt* point = ptsl+i;
	504: 	if(!point->isGood_new)
	505: 	{
	506: 		E.updateSingle((float)(point->energy[1]));
	507: 	}
	508: 	else
	509: 	{
	510: 		point->energy_new[1] = (point->idepth_new-1)*(point->idepth_new-1);
	511: 		E.updateSingle((float)(point->energy_new[1]));
	512: 	}
	513: }
	514: EAlpha.finish();
	515: float alphaEnergy = alphaW*(EAlpha.A + refToNew.translation().squaredNorm() * npts);

**Comment by JakobEngel** [comment]
yep, looks like it - however the involved parameters may not be correct any more when fixing that bug, so I'll leave it as-is at the moment. It is possibly one of the reasons why the initializer is one of the weakest points and not to be trusted, and is not included in the publications.
