### ISSUE TITLE
 the initialization of dso

### ISSUE THREAD

**Issue by califford** [JakobEngel/dso#56]
After I read the code, I am really confused about the initialization of dso, can somebody give a brief introduction or is there a related paper? Thank you very much!

**Comment by mridulkatta** [comment]
You can refer to DSO paper here: http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7898369

**Comment by JakobEngel** [comment]
Indeed, the initialization in the code is not well documented anywhere (there is no paper) and rather "hacky" (there are some bugs in the optimization performed). To be honest I didn't have time to do it properly, so it's properly not worth spending too much time onto the CoarseInitializer.
