### ISSUE TITLE
Bounty

### ISSUE THREAD

**Issue by israelshirk** [JakobEngel/dso#61]
# Whereas
Your project and research is awesome

# Findings
It's incredibly useful and is being immediately used in technology that not only makes the human experience better, but also is already being used to save lives.

# Therefore
Do you have a bounty page or paypal or anything?

# Muchos gratitude
Israel

**Comment by israelshirk** [comment]
(or an e-mail is good too, Amazon gift cards are easy to do that way)

**Comment by JakobEngel** [comment]
Thanks, great to hear! 
I don't have a bounty page, but an amazon gift card is always welcome! I added my email address to my github account, you should find it there. :)
Best, Jakob
