### ISSUE TITLE
Trying to write a c++ module to run from webcam

### ISSUE THREAD

**Issue by DxsGeorge** [JakobEngel/dso#62]
Anyone has any idea or example how is this possible? I have tried modifying the dso_ros or the dso_main_pangolin but I get eigen errors.

**Comment by DxsGeorge** [comment]
For some reason when I initialize FullSystem with 
`FullSystem *fs = new FullSystem;` 
it crashes with Eigen error on CalibHessian.h 
When I just use 
`FullSystem fs;` 
it runs.

**Comment by JakobEngel** [comment]
sounds like some alignment issue, which should be prevented by the EIGEN_MAKE_ALIGNED_OPERATOR_NEW in FullSystem.h.

**Comment by DxsGeorge** [comment]
The more weird thing is, what I have written now sometimes crashes with EIGEN error and sometimes runs completely. EIGEN must have done something really weird in 3.3 . Anyways thank you for your answer and the code of course!
