### ISSUE TITLE
Structure from VIO pose

### ISSUE THREAD

**Issue by idxExtropy** [JakobEngel/dso#65]
I am experimenting with DSO using an [InertiaCam](http://www.intersense.com/pages/70/255) from Thales.

DSO is working great and producing excellent (low noise) structure as reported in the paper!  The InertiaCam comes with properly scaled and robust VIO but no structure: [Video Here](https://www.youtube.com/watch?v=gFsVLDzHh4s).

I have been reviewing the CoarseInitializer DSO code looking for a way to use the VIO image pose to correct the structure's orientation and scale but haven't worked it out after some hours..  Does anyone have any hints as to where to start or it is borderline hopeless?  Thanks!

**Comment by NikolausDemmel** [comment]
This is addressed to some extend in #105.

Closing since the question seems answered / due to lack of activity. Feel free to continue commenting and the issue can be reopend on demand.
