### ISSUE TITLE
Typo in Readme.md

### ISSUE THREAD

**Issue by kilmarnock** [JakobEngel/dso#67]
Hi! 
Thank you for the implementation.

In the Readme.md, you say

> DSO computes the camera matrix K as

	K(0,0) = width * fx
	K(1,1) = width * fy
	K(0,2) = width * cx - 0.5
	K(1,2) = width * cy - 0.5

Should be

>     float fx = inputCalibration[0] * in_width;
        float fy = inputCalibration[1] * in_height;
        float cx = inputCalibration[2] * in_width - 0.5;
        float cy = inputCalibration[3] * in_height - 0.5;

resp. 

> K(0,0) = width * fx
	K(1,1) = height * fy
	K(0,2) = width * cx - 0.5
	K(1,2) = height * cy - 0.5

**Comment by NikolausDemmel** [comment]
See #72
