### ISSUE TITLE
How to run the code on the kitti dataset

### ISSUE THREAD

**Issue by OfirBeckerHome** [JakobEngel/dso#70]
Hello,
I am trying to run the code as is on the kitti dataset. I'm not sure how to adjust the configuration or the parameters to make it work, as the required calib/gamma/vignette don't exist in that format and the images are undistorted and rectified. Is there a written configuration for the Kitti dataset? or can you explain what needs to be done in order to run such images on the system?

Thanks!

**Comment by s3r637** [comment]
Hi @OfirBeckerHome 

see https://github.com/JakobEngel/dso/issues/51#issuecomment-300748656

cheers

**Comment by NikolausDemmel** [comment]
Closing since the question seems answered / due to lack of activity. Feel free to continue commenting and the issue can be reopend on demand.
