### ISSUE TITLE
How to setup input files for ICL-NUIM dataset?

### ISSUE THREAD

**Issue by youngguncho** [JakobEngel/dso#73]
Hi. I'm trying to use DSO on ICL-NUIM datasets.
As in the photometric calibration paper, I run DSO without pcalib and vignette files, such as

```
build/bin/dso_dataset calib=calib/calib.txt files=data/original.zip preset=0 mode=2
```

I first define the calib file as (which from ground truth calib data) 
481.20 480.0 319.50 239.50 0
640 480
none
640 480

But I got assertion error as

When using crop option
```
initial range: x: -0.6705 - 0.6705; y: -0.5039 - 0.5039!
iteration 00001: range: x: -0.6672 - 0.6672; y: -0.5039 - 0.5039!
iteration 00002: range: x: -0.6639 - 0.6639; y: -0.5039 - 0.5039!
iteration 00003: range: x: -0.6639 - 0.6639; y: -0.5014 - 0.5014!
iteration 00004: range: x: -0.6639 - 0.6639; y: -0.4989 - 0.4989!
iteration 00005: range: x: -0.6639 - 0.6639; y: -0.4989 - 0.4989!

Rectified Kamera Matrix:
481.283       0   319.5
      0 480.092   239.5
      0       0       1

NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file 
PhotometricUndistorter: Could not open file!
set timestamps and exposures to zero!
set EXPOSURES to zero!
got 879 images and 0 timestamps and 0 exposures.!
ImageFolderReader: got 879 files in data/original.zip!
using pyramid levels 0 to 3. coarsest resolution: 80 x 60!
START PANGOLIN!
OpenCV Error: Assertion failed (!buf.empty() && buf.isContinuous()) in imdecode_, file /home/yg/svn/irap/third-party/opencv-3.1.0/opencv/modules/imgcodecs/src/loadsave.cpp, line 490
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/yg/svn/irap/third-party/opencv-3.1.0/opencv/modules/imgcodecs/src/loadsave.cpp:490: error: (-215) !buf.empty() && buf.isContinuous() in function imdecode_

```

When using none option
```
Found fx=0.751875, fy=1.000000, cx=0.500000, cy=0.500000.
 I'm assuming this is the "relative" calibration file format,and will rescale this by image width / height to fx=481.200000, fy=480.000000, cx=319.500000, cy=239.500000.

Out: No Rectification
Output resolution: 640 480

Rectified Kamera Matrix:
481.2     0 319.5
    0   480 239.5
    0     0     1

NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file 
PhotometricUndistorter: Could not open file!
set timestamps and exposures to zero!
set EXPOSURES to zero!
got 879 images and 0 timestamps and 0 exposures.!
ImageFolderReader: got 879 files in data/original.zip!
using pyramid levels 0 to 3. coarsest resolution: 80 x 60!
START PANGOLIN!
OpenCV Error: Assertion failed (!buf.empty() && buf.isContinuous()) in imdecode_, file /home/yg/svn/irap/third-party/opencv-3.1.0/opencv/modules/imgcodecs/src/loadsave.cpp, line 490
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/yg/svn/irap/third-party/opencv-3.1.0/opencv/modules/imgcodecs/src/loadsave.cpp:490: error: (-215) !buf.empty() && buf.isContinuous() in function imdecode_

```

Also, I tried relative calib file as
0.751875 1 0.5 0.5 0
640 480
none (or crop)
640 480

But it shows same error also. Does this error occurs by wrong calibration data or do I need pcalib and vignette information for ICL-NUIM also?
Also, I tested sample data, it worked fine.

**Comment by NikolausDemmel** [comment]
```
Pinhole 0.751875 1.00 0.5 0.5 0
640 480
none
640 480
```

works fine for me. If you download the dataset as is, you have to make sure DSO is reading them in the correct order. By default, DSO reads them in some order

```
1.png
10.png
100.png
```

or similar. So either rename them to the expected

```
00001.png
00002.png
...
```

or adapt the sorting of files in the code.

In any case I am not sure where the error message comes from. Also, I am not reading them from a zip file, but from a directory with files, so I'm not sure if it might be different there.

**Comment by NikolausDemmel** [comment]
P.S.: Also reading from a zip file (with adapted sort order) works fine for me, so this might be a different issue. Can you run successfully with a different dataset, e.g. https://vision.in.tum.de/data/datasets/mono-dataset ?

**Comment by youngguncho** [comment]
Thank you for the reply.
As your first comment, I renamed all files with zero padded names, and it worked find!!

**Comment by NikolausDemmel** [comment]
@youngguncho, so maybe you can close this issue?

**Comment by youngguncho** [comment]
Sorry, I forgot to close the issue.
Thank you for the help!

**Comment by lichq** [comment]
Hi, I face the problem about running on my own datasets. The error information is same as above and my datasets is 1024 * 1024. Does it make problem?
