### ISSUE TITLE
Run with my own dataset issue ???

### ISSUE THREAD

**Issue by trinamntn08** [JakobEngel/dso#76]
First, i succeed to run DSO SLAM with Examples. 
So now, i want to run DSO SLAM with my own dataset. I stored my set of images in a folder. But when i run command, i got the error as images below : 

![errordso](https://user-images.githubusercontent.com/28858528/28373418-98713532-6ca2-11e7-97ed-a6433ab9615a.PNG)

Can you help me to resolve this issue.

Thanks in advance,

**Comment by NikolausDemmel** [comment]
You should start it in a debugger and check where exactly it crashes. Google is your friend for that.

**Comment by chabaudmorgan** [comment]
Before starting to debug, I would surely check the issue mentioned on the following line "PhotometricUndistorter: Invalid vignette image size! got 1280 x 1024, expected 1920 x 1080"

**Comment by trinamntn08** [comment]
@chabaudmorgan  because my own images is on format 1920x1080 , so vignette image size isn't compatible with my dataset, but i dont't think it's my main problem because i just run on mode=2 with no photometric calibrated.

**Comment by trinamntn08** [comment]
@NikolausDemmel ; sorry for my stupid question  , how can i run DSO SLAM on mode Debug . 
I lance gdb bin/dso_dataset files=./sequence_01 ...........
But it didn't work

**Comment by NikolausDemmel** [comment]
If you don't want to use vignette, you should be able to not pass the parameter instead of passing a fake one. So I guess you are using simlated data, since you use mode=2.

Passing arguments is either done with `--args` or in the `run` command of gdb. 

http://lmgtfy.com/?q=gdb+tutorial

**Comment by chabaudmorgan** [comment]
Also make sure you compile with debug information ( In CMakeLists: "set(BUILD_TYPE Debug)") instead of release.

And I agree with @NikolausDemmel , you should avoid wrong parameters when not necessary.

**Comment by trinamntn08** [comment]
I think my issue is as below: 

![errordso](https://user-images.githubusercontent.com/28858528/28408896-36adfbfe-6d39-11e7-9753-0d6494b94e22.PNG)
![errordso1](https://user-images.githubusercontent.com/28858528/28408897-36d7879e-6d39-11e7-8fff-ab494a0330f2.PNG)
I don't really understand the code in this file; Can you explain it , pls ?

**Comment by chabaudmorgan** [comment]
Could you try without changing output resolution in the calibration file?

**Comment by trinamntn08** [comment]
yes, but i got the same error

**Comment by trinamntn08** [comment]
yeah, it solved. Thanks a lot for your patient help :D

**Comment by chabaudmorgan** [comment]
What was the issue then?

Don't forget to close the issue afterwards! =)

**Comment by trinamntn08** [comment]
Just don't change the output resolution, i keep it as input resolution 1920x1080. It worked !
