### ISSUE TITLE
c++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by uncleyoung** [JakobEngel/dso#8]
All requirements have been installed/configured, and cmake .. works without any problems.(see below)
But when make, error occurred. Could anyone help, many thanks.
Following is the log.
![qq20161116-0](https://cloud.githubusercontent.com/assets/15666930/20337267/0310c7f8-ac0b-11e6-9357-c4437310d6f9.png)

**Comment by uncleyoung** [comment]
I've fixed this, it is a problem of not enough memory.

**Comment by MrDadaGuy** [comment]
For me (on ARM / Nvidia Jetson) I changed "make -j" to "make -j4" and it built successfully
