### ISSUE TITLE
Which part of code indicate the loop closure?

### ISSUE THREAD

**Issue by changliu816** [JakobEngel/dso#84]
![62618632](https://user-images.githubusercontent.com/21351731/28879506-4f5a058a-7770-11e7-92b2-db1198f9b3e2.jpg)

**Comment by NikolausDemmel** [comment]
Which loop closure are you referring to? Have you read the paper?

**Comment by changliu816** [comment]
I have used the program on road test. I drove a circle, and record the images at 60fps. However, when I did the dvo slam, the trajectory is not a close loop. Unlike the lsd_slam code where I can anchor TrackableKeyFrameSearch.cpp as loop closure detection, I failed to find where the dvo code does this job.

**Comment by NikolausDemmel** [comment]
DSO does not implement loop closure like LSD-SLAM does, it is a keyframe odometry, not a full SLAM system. Check the paper for more details.

I'll close the issue, but feel free to continue the discussion if you want to and we can re-open as needed.
