### ISSUE TITLE
Using opencv Mat

### ISSUE THREAD

**Issue by cjsb** [JakobEngel/dso#90]
Hi,

Is there any way of transforming a opecv Mat to a ImageAndExposere image?

**Comment by s3r637** [comment]
Hi @cjsb,

sure! Just take a look at the DSO source code.

cheers

**Comment by cjsb** [comment]
Do you know a specific file? Because I couldn't found alone

**Comment by fluentart** [comment]
I got this kinda working.. 
See this: https://github.com/fluentart/dso/commit/0402acd67c8e031571bb0d3499f247921a87766b

**Comment by NikolausDemmel** [comment]
I'll close this for now. Feel free to continue discussion and we can reopen if needed.
